package com.BikkadIT.AutoWiringModes.dao;

import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Repository;

@Repository
@Primary //bytype : if one of many class having @primary annotation then bean of that class will be inject.
public class MySQLReport implements ReportDao {

	@Override
	public void generateReport() {
		System.out.println("Report Generated By MySQL Database.");
		
	}

}
