package com.BikkadIT.AutoWiringModes.dao;


import org.springframework.stereotype.Repository;

@Repository
//@Primary
public class OracleReport implements ReportDao {

	@Override
	public void generateReport() {
		System.out.println("Report Generated By Oracle Database.");
		
	}

}
